#!/usr/bin/env python3
"""Shared secret-file logic for scripts/secrets-{pull,push,audit}.sh.

Subcommands
-----------
render      Infisical JSON -> .env (+ optional .claude/settings.local.json env block)
pull-plan   report what a pull would change; exit 3 when it would DOWNGRADE a real
            local value to a placeholder (the guard that stops a pull from wiping
            credentials that only exist locally)
push-plan   report what a push would change and materialise the upload file; exit 3
            when it would downgrade a real remote value
audit       key-level drift report: .env vs Infisical vs every ${VAR} the repo's
            .mcp.json files need vs .env.example vs settings.local.json

Values are never printed in full — only a masked fingerprint.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

# A value is a placeholder when it is empty or obviously a template stand-in.
PLACEHOLDER_RE = re.compile(
    r"^\s*$|replace[-_]?me|^your[-_]|\byour-[a-z0-9-]*\.example\.com|example\.com"
    r"|^changeme$|^<.*>$|^tr_dev_replace",
    re.IGNORECASE,
)


def is_placeholder(value: str | None) -> bool:
    return value is None or bool(PLACEHOLDER_RE.search(value))


def kind(value: str | None) -> str:
    if value is None:
        return "absent"
    return "placeholder" if is_placeholder(value) else "real"


def mask(value: str | None) -> str:
    if value is None:
        return "—"
    if value == "":
        return "(empty)"
    if is_placeholder(value):
        return value if len(value) <= 32 else value[:29] + "..."
    return f"{value[:4]}…({len(value)} chars)"


# --------------------------------------------------------------------------- io


def parse_env_file(path: str | os.PathLike) -> dict[str, str]:
    """Parse a dotenv file. Later assignments win, matching shell semantics."""
    out: dict[str, str] = {}
    p = Path(path)
    if not p.exists():
        return out
    for raw in p.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        out[key] = value
    return out


def duplicate_keys(path: str | os.PathLike) -> dict[str, int]:
    """Keys assigned more than once in a dotenv file — a silent-overwrite trap."""
    counts: dict[str, int] = {}
    p = Path(path)
    if not p.exists():
        return {}
    for raw in p.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key = line.split("=", 1)[0].strip()
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            counts[key] = counts.get(key, 0) + 1
    return {k: n for k, n in counts.items() if n > 1}


def load_infisical_json(path: str | os.PathLike) -> dict[str, str]:
    """Normalise whatever shape the CLI returned into an ordered {KEY: VALUE} map."""
    raw = Path(path).read_text().strip()
    if not raw:
        raise SystemExit("ERROR: empty Infisical response; files left untouched")
    try:
        data = json.loads(raw)
    except Exception as exc:  # noqa: BLE001 - message is the point
        raise SystemExit(f"ERROR: Infisical did not return valid JSON ({exc}); files left untouched")

    secrets: dict[str, str] = {}

    def add(key, value):
        if key is None:
            return
        secrets[str(key)] = "" if value is None else str(value)

    def from_item(item):
        if isinstance(item, dict):
            add(
                item.get("secretKey") or item.get("key") or item.get("name"),
                item.get("secretValue", item.get("value")),
            )

    if isinstance(data, dict):
        if isinstance(data.get("secrets"), list):
            for item in data["secrets"]:
                from_item(item)
        else:
            for key, value in data.items():
                add(key, value)
    elif isinstance(data, list):
        for item in data:
            from_item(item)

    if not secrets:
        raise SystemExit("ERROR: Infisical returned no secrets; files left untouched")
    return secrets


def sq(value: str) -> str:
    """POSIX-safe single quoting, so `$ # & = space` and multiline PEMs survive."""
    return "'" + value.replace("'", "'\\''") + "'"


def write_dotenv(path: str | os.PathLike, secrets: dict[str, str]) -> None:
    with open(path, "w") as handle:
        handle.write("# Generated by scripts/secrets-pull.sh — do not edit by hand.\n")
        handle.write("# Change a value here only to push it up: scripts/secrets-push.sh --yes\n")
        for key in sorted(secrets):
            handle.write(f"{key}={sq(secrets[key])}\n")
    os.chmod(path, 0o600)


def update_settings(path: str | os.PathLike, secrets: dict[str, str]) -> tuple[int, list[str]]:
    """Merge secrets into the `env` block, leaving every other setting alone.

    Returns (written count, orphan keys) — orphans are env entries that no longer
    exist in Infisical; they are kept (they may be hand-added) but reported.
    """
    p = Path(path)
    existing: dict = {}
    if p.exists():
        content = p.read_text().strip()
        if content:
            existing = json.loads(content)
    current_env = existing.get("env", {})
    orphans = sorted(k for k in current_env if k not in secrets)
    existing["env"] = {**current_env, **secrets}
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w") as handle:
        json.dump(existing, handle, indent=2)
        handle.write("\n")
    os.chmod(p, 0o600)
    return len(secrets), orphans


# ------------------------------------------------------------------- repo scan


def mcp_requirements(root: Path) -> dict[str, list[str]]:
    """Every ${VAR} placeholder in the repo's .mcp.json files -> which files need it."""
    needs: dict[str, list[str]] = {}
    files = [root / ".mcp.json"] + sorted(root.glob("plugins/*/.mcp.json"))
    for path in files:
        if not path.exists():
            continue
        rel = str(path.relative_to(root))
        for var in sorted(set(re.findall(r"\$\{([A-Z][A-Z0-9_]*)\}", path.read_text()))):
            needs.setdefault(var, []).append(rel)
    return needs


# --------------------------------------------------------------------- reports


def print_change_table(rows: list[tuple[str, str, str, str]]) -> None:
    if not rows:
        return
    width = max(len(r[1]) for r in rows)
    for tag, key, before, after in rows:
        print(f"   {tag:9} {key:{width}}  {before}  ->  {after}")


def cmd_render(args) -> int:
    secrets = load_infisical_json(args.json)
    if args.env_file:
        write_dotenv(args.env_file, secrets)
        print(f"   {args.env_file} written ({len(secrets)} variables, mode 600)")
    if args.settings:
        count, orphans = update_settings(args.settings, secrets)
        print(f"   {args.settings} env block updated ({count} variables, mode 600)")
        if orphans:
            print(f"   note: {len(orphans)} env entr{'y' if len(orphans)==1 else 'ies'} "
                  f"not in Infisical, left as-is: {', '.join(orphans)}")
    return 0


def cmd_pull_plan(args) -> int:
    remote = load_infisical_json(args.json)
    local = parse_env_file(args.env_file)

    added = [k for k in sorted(remote) if k not in local]
    changed = [k for k in sorted(remote) if k in local and local[k] != remote[k]]
    downgrades = [k for k in changed if kind(local[k]) == "real" and kind(remote[k]) != "real"]
    dropped = [k for k in sorted(local) if k not in remote]

    print(f"Pull plan for {args.env_file}: {len(remote)} remote keys, {len(local)} local keys")
    if added:
        print(f"\n  NEW ({len(added)}) — only in Infisical:")
        print_change_table([("add", k, "—", mask(remote[k])) for k in added])
    if changed:
        print(f"\n  CHANGED ({len(changed)}):")
        print_change_table([("update", k, mask(local[k]), mask(remote[k])) for k in changed])
    if dropped:
        print(f"\n  LOCAL-ONLY ({len(dropped)}) — will be REMOVED from {args.env_file} "
              f"(push them first if they matter):")
        print_change_table([("remove", k, mask(local[k]), "—") for k in dropped])
    if not (added or changed or dropped):
        print("\n  ✓ already in sync")

    if downgrades and not args.force:
        print(f"\n  ⛔ BLOCKED — {len(downgrades)} real local value(s) would be replaced by a "
              f"placeholder from Infisical:")
        for key in downgrades:
            print(f"       {key}: local={mask(local[key])}  remote={mask(remote[key])}")
        print("\n  Fix by pushing the local values up first:")
        print("       ./scripts/secrets-push.sh --yes")
        print("  …or overwrite them anyway:")
        print("       ./scripts/secrets-pull.sh --force")
        return 3
    if downgrades:
        print(f"\n  ⚠ --force: overwriting {len(downgrades)} real local value(s) with placeholders.")
    return 0


def cmd_push_plan(args) -> int:
    remote = load_infisical_json(args.json)
    local = parse_env_file(args.env_file)

    dupes = duplicate_keys(args.env_file)
    if dupes:
        print(f"  ⚠ duplicate assignments in {args.env_file} (last one wins): "
              + ", ".join(f"{k} x{n}" for k, n in sorted(dupes.items())))

    only = set(args.only.split(",")) if args.only else None

    add, update, blocked, same = [], [], [], []
    for key in sorted(local):
        if only and key not in only:
            continue
        value = local[key]
        if key not in remote:
            add.append(key)
        elif remote[key] == value:
            same.append(key)
        elif kind(remote[key]) == "real" and kind(value) != "real":
            blocked.append(key)
        else:
            update.append(key)

    print(f"Push plan for {args.env_file} -> Infisical: {len(local)} local keys, "
          f"{len(remote)} remote keys")
    if add:
        print(f"\n  NEW ({len(add)}) — not yet in Infisical:")
        print_change_table([("add", k, "—", mask(local[k])) for k in add])
    if update:
        print(f"\n  UPDATE ({len(update)}):")
        print_change_table([("update", k, mask(remote[k]), mask(local[k])) for k in update])
    if blocked:
        tag = "OVERWRITE (--force)" if args.force else "SKIPPED"
        print(f"\n  {tag} ({len(blocked)}) — a real remote value would become a placeholder:")
        print_change_table([("!", k, mask(remote[k]), mask(local[k])) for k in blocked])
        if not args.force:
            print("       kept as-is; pass --force to push these too")
    if same:
        print(f"\n  unchanged: {len(same)}")

    missing = sorted(set(remote) - set(local))
    if missing:
        print(f"\n  note: {len(missing)} key(s) exist in Infisical but not locally — push never "
              f"deletes, they stay: {', '.join(missing)}")

    upload = list(add) + list(update) + (list(blocked) if args.force else [])
    if args.out:
        with open(args.out, "w") as handle:
            for key in upload:
                handle.write(f"{key}={sq(local[key])}\n")
        os.chmod(args.out, 0o600)
    print(f"\n  → {len(upload)} key(s) queued for upload")
    return 0 if upload else 4  # 4 = nothing to do


def cmd_audit(args) -> int:
    root = Path(args.root).resolve()
    local = parse_env_file(args.env_file)
    remote = load_infisical_json(args.json) if args.json else {}
    example = parse_env_file(args.example) if args.example else {}
    settings_env: dict[str, str] = {}
    if args.settings and Path(args.settings).exists():
        content = Path(args.settings).read_text().strip()
        if content:
            settings_env = json.loads(content).get("env", {})

    needs = mcp_requirements(root)
    root_mcp = {v for v, files in needs.items() if ".mcp.json" in files}

    print("=" * 78)
    print("ENV AUDIT")
    print("=" * 78)
    print(f"  .env                        {len(local):>3} keys   ({args.env_file})")
    print(f"  Infisical                   {len(remote):>3} keys")
    print(f"  .env.example                {len(example):>3} keys")
    print(f"  settings.local.json env     {len(settings_env):>3} keys")
    print(f"  required by .mcp.json       {len(needs):>3} vars   "
          f"({len(root_mcp)} in the root file)")

    dupes = duplicate_keys(args.env_file)
    if dupes:
        print("\n⚠ DUPLICATE ASSIGNMENTS in .env (last wins — earlier ones are dead):")
        for key, count in sorted(dupes.items()):
            print(f"     {key} x{count}")

    print("\n" + "-" * 78)
    print("1. MCP REQUIREMENTS NOT SATISFIED (no real value in .env)")
    print("-" * 78)
    unmet = [(v, files) for v, files in sorted(needs.items()) if kind(local.get(v)) != "real"]
    if not unmet:
        print("   ✓ every ${VAR} in every .mcp.json resolves to a real value")
    for var, files in unmet:
        scope = "ROOT" if ".mcp.json" in files else "plugin"
        others = [f for f in files if f != ".mcp.json"]
        where = "root" if scope == "ROOT" else ""
        if others:
            where = (where + " + " if where else "") + f"{len(others)} plugin(s)"
        print(f"   [{scope:6}] {var:30} .env={kind(local.get(var)):11} "
              f"infisical={kind(remote.get(var)):11} ({where})")

    print("\n" + "-" * 78)
    print("2. LOCAL .env  vs  INFISICAL")
    print("-" * 78)
    only_local = sorted(set(local) - set(remote))
    only_remote = sorted(set(remote) - set(local))
    differing = sorted(k for k in set(local) & set(remote) if local[k] != remote[k])
    if only_local:
        print(f"   in .env, NOT in Infisical ({len(only_local)}) → ./scripts/secrets-push.sh")
        for key in only_local:
            print(f"       {key:30} {kind(local[key])}")
    if only_remote:
        print(f"   in Infisical, NOT in .env ({len(only_remote)}) → ./scripts/secrets-pull.sh")
        for key in only_remote:
            print(f"       {key:30} {kind(remote[key])}")
    if differing:
        print(f"   different values ({len(differing)}):")
        for key in differing:
            direction = "push" if kind(local[key]) == "real" and kind(remote[key]) != "real" else (
                "pull" if kind(remote[key]) == "real" and kind(local[key]) != "real" else "review")
            print(f"       {key:30} local={kind(local[key]):11} infisical={kind(remote[key]):11} → {direction}")
    if not (only_local or only_remote or differing):
        print("   ✓ .env and Infisical hold the same keys and values")

    print("\n" + "-" * 78)
    print("3. CATALOGUE COVERAGE (.env.example is the documented key list)")
    print("-" * 78)
    documented = set(example)
    missing_from_example = sorted((set(local) | set(needs)) - documented)
    missing_from_env = sorted(documented - set(local))
    if missing_from_example:
        print(f"   used but NOT documented in .env.example ({len(missing_from_example)}):")
        for key in missing_from_example:
            print(f"       {key}")
    if missing_from_env:
        print(f"   documented but absent from .env ({len(missing_from_env)}):")
        for key in missing_from_env:
            print(f"       {key}")
    if not (missing_from_example or missing_from_env):
        print("   ✓ .env.example and .env cover the same keys")

    print("\n" + "-" * 78)
    print("4. CLAUDE CODE SETTINGS (settings.local.json env block feeds .mcp.json)")
    print("-" * 78)
    missing_in_settings = sorted(k for k in needs if k not in settings_env)
    stale = sorted(k for k in settings_env if k in local and settings_env[k] != local[k])
    if missing_in_settings:
        print(f"   MCP vars missing from the env block ({len(missing_in_settings)}) — those MCP "
              f"servers cannot start:")
        for key in missing_in_settings:
            print(f"       {key}")
    if stale:
        print(f"   stale (settings value differs from .env) ({len(stale)}):")
        for key in stale:
            print(f"       {key}")
    if not (missing_in_settings or stale):
        print("   ✓ every MCP var is present and matches .env")

    print("\n" + "=" * 78)
    problems = len(unmet) + len(only_local) + len(only_remote) + len(differing) \
        + len(missing_from_example) + len(missing_from_env) + len(missing_in_settings) \
        + len(stale) + len(dupes)
    print(f"{problems} finding(s). Fix order: secrets-push.sh → secrets-pull.sh → restart Claude Code.")
    return 1 if problems else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("render")
    p.add_argument("--json", required=True)
    p.add_argument("--env-file", default="")
    p.add_argument("--settings", default="")
    p.set_defaults(func=cmd_render)

    p = sub.add_parser("pull-plan")
    p.add_argument("--json", required=True)
    p.add_argument("--env-file", required=True)
    p.add_argument("--force", action="store_true")
    p.set_defaults(func=cmd_pull_plan)

    p = sub.add_parser("push-plan")
    p.add_argument("--json", required=True)
    p.add_argument("--env-file", required=True)
    p.add_argument("--out", default="")
    p.add_argument("--only", default="")
    p.add_argument("--force", action="store_true")
    p.set_defaults(func=cmd_push_plan)

    p = sub.add_parser("audit")
    p.add_argument("--json", default="")
    p.add_argument("--env-file", required=True)
    p.add_argument("--example", default="")
    p.add_argument("--settings", default="")
    p.add_argument("--root", default=".")
    p.set_defaults(func=cmd_audit)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
